### ISSUE TITLE
FReplay / Pluzz - Listing des emissions en replay en erreur

### ISSUE THREAD

**Issue by camelreef** [JUL1EN094/JUL1EN094-xbmc-addons#23]
Bonjour!

Il semblerait que FranceTV ait change des choses. J'ai des erreurs avec les addons, dont voici les logs.

Les autres chaines de FReplay ont l'air de toujours bien marcher.

- FReplay

```
19:24:37.252 T:1281880992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.freplay/default.py", line 149, in <module>
                                                globalvar.channels[channel][1].list_videos(channel, param))
                                              File "/storage/.kodi/addons/plugin.video.freplay/resources/lib/channels/pluzz2.py", line 130, in list_videos
                                                jsonParserShow = json.loads(filPrgm)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
19:24:37.400 T:1962679248   ERROR: GetDirectory - Error getting plugin://plugin.video.freplay/?channel=france2&mode=shows&name=JT%2020h&param=341
19:24:37.411 T:1962679248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.freplay/?channel=france2&mode=shows&name=JT%2020h&param=341) failed
```

- Pluzz

```
19:26:20.442 T:1219531680   ERROR: Traceback (most recent call last):
19:26:20.443 T:1219531680   ERROR:   File "/storage/.kodi/addons/plugin.video.FranceTVPluzz/default.py", line 417, in <module>
19:26:20.444 T:1219531680   ERROR:     FranceTVPluzz()
19:26:20.444 T:1219531680   ERROR:   File "/storage/.kodi/addons/plugin.video.FranceTVPluzz/default.py", line 134, in __init__
19:26:20.444 T:1219531680   ERROR:     zf          = zipfile.ZipFile(CATALOG_PATH)
19:26:20.444 T:1219531680   ERROR:   File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
19:26:20.445 T:1219531680   ERROR:   File "/usr/lib/python2.7/zipfile.py", line 813, in _RealGetContents
19:26:20.445 T:1219531680   ERROR: BadZipfile: File is not a zip file
19:26:20.609 T:1962679248   ERROR: GetDirectory - Error getting plugin://plugin.video.FranceTVPluzz/?cat&iconimage=%2fstorage%2f.kodi%2faddons%2fplugin.video.FranceTVPluzz%2fresources%2fmedia%2freplay.png&mode=2&name=Replays&url=message_FT.json
19:26:20.618 T:1962679248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.FranceTVPluzz/?cat&iconimage=%2fstorage%2f.kodi%2faddons%2fplugin.video.FranceTVPluzz%2fresources%2fmedia%2freplay.png&mode=2&name=Replays&url=message_FT.json) failed

```

**Comment by jbnewbie** [comment]
Bonjour, j'ai la même erreur depuis vendredi.

**Comment by sm1090** [comment]
I encounter the same issue with Pluzz / FReplay... Not sure it will be easy to fix though.

**Comment by jbnewbie** [comment]
From news it is said that Pluzz service is over and stopped now and that the new integrated webservice is france.tv for all video and others digital contents of FranceTelevision

**Comment by Moebius2722** [comment]
Work with FReplay.

**Comment by essembeh** [comment]
Bonjour

Le zip avec les json n'est plus dispo, par contre il existe una API assez similaire pour avoir le listing des programmes:
http://pluzz.webservices.francetelevisions.fr/pluzz/liste/type/replay/nb/10000/chaine/france2 (france3, france4, france5, franceo)

Ce qui change c'est que l'URL de la playlist du stream n'est plus dans le json, il faut appeler une seconde API avec l'ID:
http://webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=%s&catalogue=Pluzz

Là on retrouve les URL des playlist "classiques", j'ai noté que la HD n'est dispo que dans celle "hls_v5_os" (ayant le standard5).

Bon j'ai rien inventé, j'ai eu besoin d'adapter une app perso en lisant le code de https://github.com/SylvainCecchetto/plugin.video.catchuptvandmore :)

 ++

**Comment by spmjc** [comment]
Merci pour la recherche.
J'essaierai de faire des maj. Mais ça sera pas sur tout de suite.
Si tu veux te lancer, n hésite pas :)

**Comment by camelreef** [comment]
Et si on demande super gentiment, on pourrait esperer?
Pretty pleaaaase?????

**Comment by spmjc** [comment]
Je pars bientôt en vacances. Je doute que je puisse le faire avant de
partir.
Pretty dsl

**Comment by camelreef** [comment]
Pretty déçu!
Mais on peut attendre le retour!

**Comment by wwp** [comment]
Confirmé, c'est broken actuellement ("File is not a zip file"), du coup rien dans Directs et seulement la liste des chaînes dans Replay.
